services:
  # Fusio container
  fusio:
    image: fusio/fusio
    restart: always
    networks:
      - traefik_network
    environment:
      FUSIO_TENANT_ID: "1"
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_URL: "http://api.mvmdev.com"
      FUSIO_APPS_URL: "http://apps.mvmdev.com"
      FUSIO_ENV: "prod"
      FUSIO_DEBUG: "true"
      FUSIO_CONNECTION: "pdo-mysql://fusio:61ad6c6A5999@mysql-fusio/fusio"
      FUSIO_BACKEND_USER: "maycon"
      FUSIO_BACKEND_EMAIL: "maycon@mvmdev.com"
      FUSIO_BACKEND_PW: "Sync@M1122"
      FUSIO_MAILER: "native://default"
      FUSIO_MESSENGER: "doctrine://default"
      FUSIO_MAIL_SENDER: "info@api.fusio.cloud"
      FUSIO_WORKER_JAVA: "worker-java:9090"
      FUSIO_WORKER_JAVASCRIPT: "worker-javascript:9091"
      FUSIO_WORKER_PHP: "worker-php:9092"
      FUSIO_WORKER_PYTHON: "worker-python:9093"
    links:
      - mysql-fusio
      - worker-java
      - worker-javascript
      - worker-php
      - worker-python
    ports:
      - "8484:80"
    volumes:
      - /mvm/Bancos_de_Dados:/mvm/Bancos_de_Dados
    labels:
      - "traefik.http.routers.fusio.rule=Host(`api.mvmdev.com`) || Host(`apps.mvmdev.com`)"
      - "traefik.http.routers.fusio.entrypoints=websecure"
      - "traefik.http.routers.fusio.tls.certresolver=myresolver"
      - "traefik.http.services.fusio.loadbalancer.server.port=80"

  # Fusio system database
  mysql-fusio:
    image: mysql:8.0
    restart: always
    networks:
      - traefik_network
    environment:
      MYSQL_ROOT_PASSWORD: "61ad6c6A5999"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c6A5999"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db:/var/lib/mysql

  # Worker containers
  worker-java:
    image: fusio/worker-java:2.0
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./worker/java:/worker/actions

  worker-javascript:
    image: fusio/worker-javascript:2.0
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./worker/javascript:/worker/actions

  worker-php:
    image: fusio/worker-php:2.1
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./worker/php:/var/www/html/worker/actions

  worker-python:
    image: fusio/worker-python:2.0
    restart: always
    networks:
      - traefik_network
    volumes:
      - ./worker/python:/worker/actions

networks:
  traefik_network:
    driver: bridge
