version: '3'
services:
  # Fusio container
  fusio:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    links:
      - mysql-fusio
      - worker-java
      - worker-javascript
      - worker-php
      - worker-python
    ports:
      - "8484:80"
    volumes:
      - ./fusio:/var/www/html/fusio
      - ./logs:/var/www/html/fusio/log
      - ./cache:/var/www/html/fusio/cache
      - /mvm/Bancos_de_Dados:/mvm/Bancos_de_Dados

  # Fusio system database
  mysql-fusio:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "61ad6c6A5999"
      MYSQL_USER: "fusio"
      MYSQL_PASSWORD: "61ad6c6A5999"
      MYSQL_DATABASE: "fusio"
    volumes:
      - ./db:/var/lib/mysql

  # Worker
  worker-java:
    image: fusio/worker-java:2.0
    restart: always
    volumes:
      - ./worker/java:/worker/actions
  worker-javascript:
    image: fusio/worker-javascript:2.0
    restart: always
    volumes:
      - ./worker/javascript:/worker/actions
  worker-php:
    image: fusio/worker-php:2.1
    restart: always
    volumes:
      - ./worker/php:/var/www/html/worker/actions
  worker-python:
    image: fusio/worker-python:2.0
    restart: always
    volumes:
      - ./worker/python:/worker/actions
